package GUI;

import Model.Pair;
import Model.User;
import Model.UserOverflowException;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;



/**
 * Class ComunioIntro.
 * The Messenger introducer interface.
 * @author Juan Luis
 */
public class ComunioIntro extends javax.swing.JDialog {

    /**
     * User's name.
     */
    private String user;
    
    /**
     * User's password.
     */
    private char[] password;
    
    /**
     * Checks if the name is ok.
     */
    private boolean validName;
    
    /**
     * Creates new form MSNIntro
     */
    public ComunioIntro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setValidName(false);
        this.addWindowListener (new WindowAdapter() {
            @Override
            public void windowClosing (WindowEvent e) {
                System.exit(0);
            }
        });
        
        
        this.setTitle(Data.Txt.PROGRAM_NAME);
        this.labelWelcome.setText("BIENVENIDO A "+Data.Txt.PROGRAM_NAME);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelWelcome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelAuthor = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelEdition = new javax.swing.JLabel();
        labelCopyright = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        labelAskName = new javax.swing.JLabel();
        btStart = new javax.swing.JButton();
        labelAskName1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btStart1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dropbox MSN");
        setAlwaysOnTop(true);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Media/football_icon.png")));
        setMaximumSize(new java.awt.Dimension(350, 500));
        setMinimumSize(new java.awt.Dimension(350, 500));
        setResizable(false);

        labelWelcome.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        labelWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWelcome.setText("BIENVENIDO A NO MORE COMUNIO");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/football_icon.png"))); // NOI18N
        jLabel1.setToolTipText("");

        labelAuthor.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        labelAuthor.setForeground(new java.awt.Color(0, 0, 255));
        labelAuthor.setText("Grupo DDSI");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(Data.Txt.VERSION);

        labelEdition.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        labelEdition.setForeground(new java.awt.Color(0, 0, 255));
        labelEdition.setText("No More Comunio");

        labelCopyright.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        labelCopyright.setForeground(new java.awt.Color(0, 0, 255));
        labelCopyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCopyright.setText(Data.Txt.COPYRIGHT + " ");

        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserNameKeyReleased(evt);
            }
        });

        labelAskName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelAskName.setText("Introduzca un nombre para iniciar sesión:");

        btStart.setBackground(new java.awt.Color(0, 0, 255));
        btStart.setForeground(new java.awt.Color(255, 255, 255));
        btStart.setText("Iniciar sesión");
        btStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartActionPerformed(evt);
            }
        });

        labelAskName1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelAskName1.setText("Contraseña:");

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        btStart1.setBackground(new java.awt.Color(0, 204, 51));
        btStart1.setForeground(new java.awt.Color(255, 255, 255));
        btStart1.setText("Registrarse");
        btStart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStart1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUserName)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(labelEdition)
                                                .addComponent(labelAuthor))
                                            .addGap(177, 177, 177)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(labelCopyright)
                                                .addComponent(jLabel2)))
                                        .addComponent(labelAskName))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btStart)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btStart1))
                                    .addComponent(labelAskName1)
                                    .addComponent(txtPassword))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAuthor)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEdition)
                    .addComponent(labelCopyright))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelAskName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelAskName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btStart)
                    .addComponent(btStart1))
                .addGap(29, 29, 29))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Set the validity of user name and enables starting button if needed.
     * @param valid Boolean indicating name's validity.
     */
    private void setValidName(boolean valid){
        validName = valid;
        btStart.setEnabled(validName);
    }
    
    /**
     * Reads the user name and inits the messenger.
     */
    private void performReadName(){
        user = this.txtUserName.getText();
        password = this.txtPassword.getPassword();
        this.dispose();
    }
    
    /**
     * Start button event.
     * @param evt 
     */
    private void btStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartActionPerformed
        if(validName) performReadName();
    }//GEN-LAST:event_btStartActionPerformed

    /**
     * Enter pressing event.
     * @param evt 
     */
    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        if(validName) performReadName();
    }//GEN-LAST:event_txtUserNameActionPerformed

    /**
     * Key released event. Sets validity of the name.
     * @param evt 
     */
    private void txtUserNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyReleased
        setValidName(!txtUserName.getText().trim().isEmpty());
    }//GEN-LAST:event_txtUserNameKeyReleased

    private void btStart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStart1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btStart1ActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        if(validName) performReadName();
    }//GEN-LAST:event_txtPasswordActionPerformed

    /**
     * Shows the view to get the user name.
     * @return 
     */
    public Pair<String,char[]> getUser(){
        this.setVisible(true);
        return new Pair(user,password);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btStart;
    private javax.swing.JButton btStart1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelAskName;
    private javax.swing.JLabel labelAskName1;
    private javax.swing.JLabel labelAuthor;
    private javax.swing.JLabel labelCopyright;
    private javax.swing.JLabel labelEdition;
    private javax.swing.JLabel labelWelcome;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
